### ISSUE TITLE
Add SAT as "Fiat currency for device" or have it as an option

### ISSUE THREAD

**Issue by AxelHamburch** [lnbits/lnurldevice#4]
Bitcoin Satoshis is not a FIAT unit, but it would greatly enrich the function of LNURLDevice devices like LNPoS and the bitcoinSwitch if the unit SAT could be added for Satoshis. It is always very hard to explain that with a bitcoin Lightning device, you cannot nominate the payment in Satoshis. I can only assume that it is because the library used for FIAT conversion, does not support the unit "Sats". But maybe a solution can be found after all. The interest is in any case very large.

In a pinch, an option to select when creating the LNURLDevice instance. Then there is only the unit Sats. A conversion is neither possible nor necessary. Why also in a hyperbitcoinized world? 🤩

![2023-04-01 17_25_53-LNbits🍺](https://user-images.githubusercontent.com/84231978/229299732-d6b7ff0a-c30c-4915-8232-42847c6925fb.png)

**Comment by dni** [comment]
#7 should fix it

**Comment by AxelHamburch** [comment]
I have tested it on two LNbits servers. I did not get it to run. It does not show me any "sats". :(

I have uninstalled the extension, git pull and reinstalled. Everything remains the same as before. It still does not work. Can how to open the issue again?
